[tool.poetry]
name = "nilmtk"
version = "0.1.0"
description = "Estimate the energy consumer by individual appliances from whole-house power meter readings"
authors = ["Emilio J. Palacios-Garcia <emiliojose.palaciosgarcia@kuleuven.be>"]
license = "\"Apache 2.0\""
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9,<3.12"
pandas = "^1.5.3"
numpy = "^1.24.2"
networkx = "^3.0"
scipy = "^1.10.1"
tables = "^3.8.0"
scikit-learn = "^1.2.2"
hmmlearn = "^0.2.8"
PyYAML = "^6.0"
matplotlib = "^3.7.1"
jupyterlab = "^3.6.3"
nilm-metadata = {path = "../nilm_metadata", develop = true}
pytz = "^2023.3"


[tool.poetry.group.test.dependencies]
nose = "^1.3.7"


[tool.poetry.group.dev.dependencies]
black = "^23.3.0"
isort = "^5.12.0"
mypy = "^1.1.1"

[tool.isort]
profile = "black"

[[tool.mypy.overrides]]
ignore_missing_imports = true
module = [
"python",
"pandas",
"numpy",
"networkx",
"scipy",
"tables",
"sklearn.*",
"hmmlearn",
"PyYAML",
"matplotlib.*",
"jupyterlab",
"nilm-metadata",
    "pytz"
]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


